# Generated by Django 4.0.7 on 2022-12-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='portafolio_uuid',
            new_name='tag_uuid',
        ),
    ]
