
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAIL = 'GET_PROJECT_LIST_FAIL';
    

export const GET_PROJECT_PAGINATION_RESULTS_SUCCESS = 'GET_BLOG_PAGINATION_RESULTS_SUCCESS';
export const GET_PROJECT_PAGINATION_RESULTS_FAIL = 'GET_BLOG_PAGINATION_RESULTS_FAIL';
